import { Toaster } from "react-hot-toast";
import "./globals.css";
import Header from "@/components/header";
import ClientComponent from "../components/ClientComponent/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>
          <ClientComponent>{children}</ClientComponent>
        </div>
      </body>
    </html>
  );
}
